name = "sofian-store"
compatibility_date = "2026-09-15"
pages_build_output_dir = "dist/public"

[[d1_databases]]
binding = "DB"
database_name = "luma-store-db"
database_id = "8ef5d0f8-90fa-4101-aa66-55c9480a01bc"

migrations_dir = "drizzle"

[vars]
STORE_NAME = "Sofian Store"
DEFAULT_LOCALE = "ar"

[[kv_namespaces]]
binding = "STORE_KV"
id = "fe71a20cbc84485cbb8dab80d470bd4f"
