import { useState } from "react";
import { Check } from "lucide-react";

export default function AdminSettings({ arabic, primary, secondary, onPrimaryChange, onSecondaryChange }: { arabic: boolean; primary: string; secondary: string; onPrimaryChange: (value: string) => void; onSecondaryChange: (value: string) => void }) {
  const [announcement, setAnnouncement] = useState(true);
  const [saved, setSaved] = useState(false);
  const save = async () => { await fetch("/api/admin/settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ primaryColor: primary, secondaryColor: secondary, announcementEnabled: announcement }) }); setSaved(true); window.setTimeout(() => setSaved(false), 1800); };
  return <div className="page-view"><div className="page-title"><div><span className="admin-eyebrow">LUMA / SETTINGS</span><h1>{arabic ? "الإعدادات" : "Settings"}</h1><p>{arabic ? "الإعدادات العامة والتكاملات." : "General settings and integrations."}</p></div><button className="admin-primary" onClick={save}>{saved ? <><Check size={15} />{arabic ? "تم الحفظ" : "Saved"}</> : arabic ? "حفظ التغييرات" : "Save changes"}</button></div><section className="admin-panel form-panel settings-single"><div className="panel-heading"><div><h2>{arabic ? "تخصيص المظهر" : "Customize appearance"}</h2><span>{arabic ? "يتم تطبيق الألوان فورًا على واجهة المتجر" : "Colors apply instantly to the storefront"}</span></div></div><div className="color-fields"><label>{arabic ? "اللون الأساسي" : "Primary color"}<span className="color-preview" style={{ background: primary }} /><input type="color" value={primary} onChange={(e) => onPrimaryChange(e.target.value)} /></label><label>{arabic ? "اللون الثانوي" : "Secondary color"}<span className="color-preview" style={{ background: secondary }} /><input type="color" value={secondary} onChange={(e) => onSecondaryChange(e.target.value)} /></label></div><div className="setting-switch"><div><b>{arabic ? "إظهار شريط الإعلان" : "Show announcement bar"}</b><span>{arabic ? "إظهار شريط المؤقت والإعلان أعلى الصفحة" : "Show the timer and announcement bar"}</span></div><button className={announcement ? "toggle on" : "toggle"} onClick={() => setAnnouncement(!announcement)}><i /></button></div><label>{arabic ? "رقم واتساب التاجر" : "Merchant WhatsApp number"}<input placeholder="9627XXXXXXXX" /></label><label>{arabic ? "Meta Pixel ID" : "Meta Pixel ID"}<input placeholder="Optional" /></label><label>{arabic ? "TikTok Pixel ID" : "TikTok Pixel ID"}<input placeholder="Optional" /></label><p className="settings-note">{arabic ? "مفاتيح CAPI تحفظ كـ Secrets في Cloudflare ولا تظهر في الواجهة." : "CAPI keys should be stored as Cloudflare Secrets and never exposed to the browser."}</p></section></div>;
}
