import { FormEvent, useEffect, useState } from "react";
import { Plus } from "lucide-react";

export default function AdminShipping({ arabic, t }: { arabic: boolean; t: { shipping: string } }) {
  const [zones, setZones] = useState<Array<Record<string, unknown>>>([]);
  const [countryCode, setCountryCode] = useState("JO");
  const [countryName, setCountryName] = useState(arabic ? "الأردن" : "Jordan");
  const [region, setRegion] = useState("");
  const [price, setPrice] = useState("0");
  useEffect(() => { fetch("/api/admin/shipping").then((r) => r.ok ? r.json() : { zones: [] }).then((data) => setZones((data as { zones?: Array<Record<string, unknown>> }).zones ?? [])).catch(() => setZones([])); }, []);
  const addZone = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const item = { countryCode, countryName, regionName: region, priceCents: Number(price) * 100 }; await fetch("/api/admin/shipping", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(item) }); setZones((items) => [...items, { country_code: countryCode, country_name: countryName, region_name: region, price_cents: item.priceCents }]); setRegion(""); };
  return <div className="page-view"><div className="page-title"><div><span className="admin-eyebrow">LUMA / SHIPPING</span><h1>{t.shipping}</h1><p>{arabic ? "أضف المناطق وحدد سعر الشحن لكل محافظة." : "Add regions and set a shipping price for each one."}</p></div></div><div className="settings-grid"><section className="admin-panel form-panel"><div className="panel-heading"><div><h2>{arabic ? "إضافة منطقة" : "Add a region"}</h2><span>{arabic ? "يتم حفظها في D1" : "Saved to D1"}</span></div></div><form onSubmit={addZone}><label>{arabic ? "الدولة" : "Country"}<select value={countryCode} onChange={(e) => { setCountryCode(e.target.value); setCountryName(e.target.options[e.target.selectedIndex].text); }}><option value="JO">{arabic ? "الأردن" : "Jordan"}</option><option value="SA">{arabic ? "السعودية" : "Saudi Arabia"}</option><option value="AE">{arabic ? "الإمارات" : "United Arab Emirates"}</option><option value="EG">{arabic ? "مصر" : "Egypt"}</option><option value="LY">{arabic ? "ليبيا" : "Libya"}</option></select></label><label>{arabic ? "المحافظة / المنطقة" : "Region"}<input required value={region} onChange={(e) => setRegion(e.target.value)} placeholder={arabic ? "عمّان" : "Amman"} /></label><label>{arabic ? "سعر الشحن" : "Shipping price"}<input required type="number" min="0" value={price} onChange={(e) => setPrice(e.target.value)} /></label><button className="admin-primary" type="submit"><Plus size={15} />{arabic ? "إضافة المنطقة" : "Add region"}</button></form></section><section className="admin-panel form-panel"><div className="panel-heading"><div><h2>{arabic ? "المناطق الحالية" : "Current regions"}</h2><span>{zones.length} {arabic ? "منطقة" : "regions"}</span></div></div><div className="zone-list">{zones.length === 0 ? <div className="empty-table">{arabic ? "لم تتم إضافة مناطق بعد" : "No regions added yet"}</div> : zones.map((zone, index) => <div className="zone-row" key={`${String(zone.country_code)}-${String(zone.region_name)}-${index}`}><span><b>{String(zone.region_name)}</b><small>{String(zone.country_name)}</small></span><strong>${(Number(zone.price_cents ?? 0) / 100).toFixed(2)}</strong></div>)}</div></section></div></div>;
}
